#!/usr/bin/env bash
apm install unity-ui

apm install \
  advanced-open-file \
  atom-beautify \
  autoclose-html \
  color-picker \
  docblockr \
  emmet \
  expose \
  file-icons \
  git-plus \
  gitignore-snippets \
  hex \
  language-docker \
  language-ignore \
  language-swift \
  language-vue \
  linter \
  linter-docker \
  linter-golinter \
  linter-js-yaml \
  linter-jscs \
  linter-jsonlint \
  linter-markdown \
  linter-pylint \
  linter-ruby \
  linter-scss-lint \
  linter-swiftc \
  linter-tidy \
  open-in-browser \
  pigments \
  python-isort \
  react \
  regex-railroad-diagram \
  sort-lines \
  terminal-plus \
  todo-show \
  tool-bar \
  tool-bar-atom \
  travis-ci-status \
  tree-view-git-status \
