default-cache-ttl 600
max-cache-ttl 7200
allow-loopback-pinentry
# pinentry-program /opt/homebrew/bin/pinentry-mac # Use pinentry-mac on macOS
# pinentry-program /usr/bin/pinentry-tty          # Use pinentry-tty on Linux
