---
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: kubernetes
spec:
  hosts:
    - role: controller+worker
      noTaints: true
      # privateAddress: 127.0.0.1
      # privateInterface: eth0
      ssh:
        address: 127.0.0.1
        keyPath: ~/.ssh/id_ed25519
        port: 22
        user: ubuntu
      # installFlags:
      #   - --disable-components=metrics-server
      #   - --enable-cloud-provider
      #   - --kubelet-extra-args=--cgroup-driver=systemd
      #   - --kubelet-extra-args=--cloud-provider=external
      #   - --labels=openebs.io/nodeid=$(hostname)
      #   - --labels=openstack-compute-node=enabled
      #   - --labels=openstack-control-plane=enabled
      #   - --labels=openstack-gateway=enabled
      #   - --labels=openvswitch=enabled
      # files:
      #   - # audit policy
      #     name: audit
      #     src: ./config/audit-policy.yaml
      #     dst: /var/lib/k0s/audit-policy.yaml
      #   - # containerd patch
      #     name: containerd
      #     src: ./config/containerd.toml
      #     dst: /etc/k0s/containerd.d/systemd.toml
      #   - # custom resources definitions
      #     name: crds
      #     src: ./crds
      #     dstDir: /var/lib/k0s/manifests/crds
      hooks:
        apply:
          before:
            - echo "Preparing $(hostname) control+worker node"
          after:
            - echo "$(hostname) control+worker node ready"
  k0s:
    version: v1.35.2+k0s.0
    config: {}
