---
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: kubernetes
spec:
  api:
    address: 127.0.0.1
    # externalAddress: 127.0.0.1
    # onlyBindToAddress: true
    sans:
      - kubernetes.local
      - 127.0.0.1
      - ::1
    extraArgs:
      # audit-log-maxage: "30"
      # audit-log-maxbackup: "10"
      # audit-log-maxsize: "100"
      # audit-log-path: /var/log/kubernetes/audit.log
      # audit-policy-files: /var/lib/k0s/audit-policy.yaml
      kubelet-preferred-address-types: InternalIP,Hostname,ExternalIP
  # storage:
  #   etcd:
  #     peerAddress: 127.0.0.1
  network:
    provider: custom
    # podCIDR: 10.244.0.0/16
    # serviceCIDR: 10.96.0.0/12
    # primaryAddressFamily: IPv4
    # dualStack:
    #   enabled: true
    #   IPv6podCIDR: fd00:10:244::0/112
    #   IPv6serviceCIDR: fd00:10:96::0/108
    kubeProxy:
      disabled: false
      mode: nftables
      # metricsBindAddress: 127.0.0.1:10249
  featureGates:
    - name: UserNamespacesSupport
      enabled: true
  extensions:
    helm:
      charts:
        - name: cilium
          chartname: oci://ghcr.io/labsonline/charts/cni
          namespace: kube-system
          order: 1
          version: 1.0.7
          values: |
            cilium:
              enabled: true
              kubeProxyReplacement: true
              # k8sServiceHost: 127.0.0.1
              k8sServicePort: 6443
              # cni:
              #   exclusive: false
              # encryption:
              #   enabled: true
              #   type: wireguard
              # ipv6:
              #   enabled: true
              operator:
                replicas: 1
              # hubble:
              #   relay:
              #     enabled: true
              #   ui:
              #     enabled: true
              # nodePort:
              #   addresses:
              #     - 127.0.0.0/8
              #     - ::1/128
              # bpf:
              #   hostLegacyRouting: true
              # bgpControlPlane:
              #   enabled: false
              l2:
                enabled: true
                # interfaces:
                #   - eth0
              bgp:
                enabled: true
                peer:
                  # authSecretRef: ""
                  addressFamilies: []
                    # - afi: ipv4
                    #   safi: unicast
                    #   advertisements:
                    #     matchLabels:
                    #       advertise: bgp
                    # - afi: ipv6
                    #   safi: unicast
                    #   advertisements:
                    #     matchLabels:
                    #       advertise: bgp
                instances: []
                  # - name: rt
                  #   localASN: 65000
                  #   overrides:
                  #     enabled: true
                  #   peers: []
                  #     # - name: rtv4
                  #     #   # localAddress: 127.0.0.1
                  #     #   peerASN: 65000
                  #     #   peerAddress: 127.0.0.1
                  #     #   peerConfigRef:
                  #     #     name: bgp-peer-config
                  #     # - name: rtv6
                  #     #   # localAddress: ::1
                  #     #   peerASN: 65000
                  #     #   peerAddress: ::1
                  #     #   peerConfigRef:
                  #     #     name: bgp-peer-config
              pool:
                enabled: true
                # blocks:
                #   - cidr: 172.16.0.192/27
                #   - cidr: fd00:172:16:0::192/123
        - name: openebs
          chartname: oci://ghcr.io/labsonline/charts/csi
          namespace: kube-system
          order: 2
          version: 1.0.7
          # values: |
          #   openebs:
          #     openebs-crds:
          #       csi:
          #         volumeSnapshots:
          #           enabled: true
          #     lvm-localpv:
          #       lvmNode:
          #         kubeletDir: /var/lib/k0s/kubelet/
          #       class:
          #         volgroup: openebs-vg
          #     # zfs-localpv:
          #     #   zfsNode:
          #     #     kubeletDir: /var/lib/k0s/kubelet/
          #     #   class:
          #     #     poolname: openebs
          #     localpv-provisioner:
          #       hostpathClass:
          #         enabled: false
          #       localpv:
          #         enabled: false
          #     # mayastor:
          #     #   crds:
          #     #     csi:
          #     #       volumeSnapshots:
          #     #         className: openebs-single-replica
          #     #         deletionPolicy: Delete
          #     #   storageClass:
          #     #     nameSuffix: single-replica
          #     #     default: true
          #     #     # parameters:
          #     #     #   repl: 1
          #     #     #   protocol: nvmf
          #     #     #   encrypted: true
          #     #   # io_engine:
          #     #   #   target:
          #     #   #     nvmf:
          #     #   #       iface: rxe0
          #     #   #       rdma:
          #     #   #         enabled: true
          #     engines:
          #       local:
          #         lvm:
          #           enabled: true
          #       #   zfs:
          #       #     enabled: true
          #       # replicated:
          #       #   mayastor:
          #       #     enabled: true
  telemetry:
    enabled: false
