#cloud-config
fqdn: ubuntu.local
hostname: ubuntu
manage_etc_hosts: true
package_update: true
package_upgrade: true
timezone: Etc/UTC
growpart:
  mode: auto
  ignore_growroot_disabled: false
  devices: [/]
users:
  - default
ssh_authorized_keys: []
ntp:
  pools:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    - 2.pool.ntp.org
    - 3.pool.ntp.org
write_files:
  - path: /usr/lib/systemd/system/user@.service.d/delegate.conf
    permissions: "0644"
    owner: root
    content: |
      [Service]
      Delegate=cpu cpuset io memory pids
  - path: /etc/environment
    permissions: "0644"
    owner: root
    content: |
      PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
      EDITOR="vim"
      PAGER="cat"
