#cloud-config
apt:
  sources:
    docker.list:
      source: deb https://download.docker.com/linux/ubuntu noble stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
packages:
  - containerd.io
  - docker-ce
  - docker-ce-cli
