network:
  version: 2
  bonds:
    bond0:
      accept-ra: true
      dhcp4: true
      dhcp6: true
      mtu: 9000
      optional: true
      parameters:
        mode: 802.3ad
        lacp-rate: fast
        mii-monitor-interval: 100
        transmit-hash-policy: layer3+4
