name: Continuos Integration

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  bot:
    uses: anselmes/cicd/.github/workflows/bot.yml@672a6e6bcac471a729b0013daa38fc0512600f5a # v0.2.0
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: write

  trivy:
    uses: anselmes/cicd/.github/workflows/trivy.yml@672a6e6bcac471a729b0013daa38fc0512600f5a # v0.2.0
    permissions:
      contents: write
      id-token: write
      security-events: write

  scorecard:
    uses: anselmes/cicd/.github/workflows/scorecard.yml@672a6e6bcac471a729b0013daa38fc0512600f5a # v0.2.0
    permissions:
      contents: read
      id-token: write
      security-events: write
